   /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myctu.touristmanagementsystem.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.BorderFactory;
import javax.swing.JMenuBar;

/**
 *
 * @author ASUS
 */
public class AdminView extends javax.swing.JFrame {

    private DanhSachDatTour danhSachDatTourn = new DanhSachDatTour();
    private QuanLyTour quanLyTour = new QuanLyTour();
    private ThongKeBaoCao thongKeBaoCao = new ThongKeBaoCao();

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
        initPanel();
        customizeView();
        this.setLocationRelativeTo(this);
    }

    private void customizeView() {
        menuAdmin = new JMenuBar() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                // Vẽ nền gradient cho thanh menu
                Graphics2D g2d = (Graphics2D) g;
                int width = getWidth();
                int height = getHeight();

                // Gradient từ màu xám nhạt đến trắng
                GradientPaint gp = new GradientPaint(0, 0, Color.LIGHT_GRAY, 0, height, Color.WHITE);
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, width, height);
            }
        };

        mnDsDatTour.setFont(new Font("Arial", Font.PLAIN, 14));
        mnQuanLyTour.setFont(new Font("Arial", Font.PLAIN, 14));
        menuAdmin.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        menuAdmin.repaint();
    }

    private void initPanel() {

        pnMainAdmin.add(quanLyTour);
        pnMainAdmin.add(danhSachDatTourn);
        pnMainAdmin.add(thongKeBaoCao);
        danhSachDatTourn.setVisible(false);
        quanLyTour.setVisible(false);
        thongKeBaoCao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnMainAdmin = new javax.swing.JLayeredPane();
        menuAdmin = new javax.swing.JMenuBar();
        mnHeThong = new javax.swing.JMenu();
        mnQuanLyTour = new javax.swing.JMenuItem();
        mnDsDatTour = new javax.swing.JMenuItem();
        mnBaoCaoThongKe = new javax.swing.JMenuItem();
        mnHoSo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        pnMainAdmin.setPreferredSize(new java.awt.Dimension(600, 327));
        pnMainAdmin.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnMainAdmin, java.awt.BorderLayout.CENTER);

        mnHeThong.setText("Hệ Thống");

        mnQuanLyTour.setText("Quản lý tour");
        mnQuanLyTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuanLyTourActionPerformed(evt);
            }
        });
        mnHeThong.add(mnQuanLyTour);

        mnDsDatTour.setText("Danh sách đặt tour");
        mnDsDatTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDsDatTourActionPerformed(evt);
            }
        });
        mnHeThong.add(mnDsDatTour);

        mnBaoCaoThongKe.setText("Báo cáo thống kê");
        mnBaoCaoThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBaoCaoThongKeActionPerformed(evt);
            }
        });
        mnHeThong.add(mnBaoCaoThongKe);

        menuAdmin.add(mnHeThong);

        mnHoSo.setText("Hồ sơ");

        jMenuItem1.setText("Edit");
        jMenuItem1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jMenuItem1AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnHoSo.add(jMenuItem1);

        jMenuItem2.setText("logOut");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnHoSo.add(jMenuItem2);

        menuAdmin.add(mnHoSo);

        setJMenuBar(menuAdmin);

        setBounds(0, 0, 612, 356);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginView loginview = new LoginView();
        loginview.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AdminInformationView adminIF = new AdminInformationView();
        adminIF.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuItem1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1AncestorMoved

    private void mnDsDatTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDsDatTourActionPerformed

        quanLyTour.setVisible(false);
        danhSachDatTourn.setVisible(true);

    }//GEN-LAST:event_mnDsDatTourActionPerformed

    private void mnQuanLyTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuanLyTourActionPerformed
        danhSachDatTourn.setVisible(false);
        quanLyTour.setVisible(true);
    }//GEN-LAST:event_mnQuanLyTourActionPerformed

    private void mnBaoCaoThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBaoCaoThongKeActionPerformed
        // TODO add your handling code here:
        danhSachDatTourn.setVisible(false);
        quanLyTour.setVisible(false);
        thongKeBaoCao.setVisible(true);
    }//GEN-LAST:event_mnBaoCaoThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JMenuItem mnBaoCaoThongKe;
    private javax.swing.JMenuItem mnDsDatTour;
    private javax.swing.JMenu mnHeThong;
    private javax.swing.JMenu mnHoSo;
    private javax.swing.JMenuItem mnQuanLyTour;
    private javax.swing.JLayeredPane pnMainAdmin;
    // End of variables declaration//GEN-END:variables
}
